# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Address',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Department',
            new_name='Phone',
        ),
    ]
